name: Download and Publish GSI ROM

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release GSI ROM

    steps:
      - name: Set up
        run: sudo apt update && sudo apt install -y p7zip-full

      - name: Download LineageOS GSI
        run: |
          wget -O lineage-gsi.7z "https://downloads.sourceforge.net/project/misterztr-gsi/LineageOS/Android%2015/LineageOS-22.2-20250509-GAPPS-EROFS-GSI.7z"

      - name: Extract GSI
        run: |
          7z x lineage-gsi.7z -olineage-gsi

      - name: Zip extracted image
        run: |
          cd lineage-gsi
          zip -r ../LineageOS-22.2-GSI.zip *

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: LineageOS 22.2 GSI
          tag_name: lineageos-gsi-22.2
          files: LineageOS-22.2-GSI.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
