name: Inject Magisk into LineageOS GSI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Install required packages
        run: |
          sudo apt update
          sudo apt install -y p7zip-full curl zip

      - name: Download LineageOS GSI
        run: |
          mkdir gsi && cd gsi
          curl -L -o lineage-gsi.7z "https://sourceforge.net/projects/misterztr-gsi/files/LineageOS/Android%2015/LineageOS-22.2-20250509-GAPPS-EROFS-GSI.7z/download"

      - name: Extract GSI
        run: |
          cd gsi
          7z x lineage-gsi.7z -ogsi-extracted

      - name: Download Magisk v31.0
        run: |
          mkdir magisk && cd magisk
          curl -L -o Magisk-v31.0.apk "https://github.com/topjohnwu/magisk/releases/download/v31.0/Magisk-v31.0.apk"

      - name: Simulate Magisk Injection
        run: |
          mkdir workdir
          cp $(find gsi/gsi-extracted -name "*.img" | head -n 1) workdir/system.img
          cp magisk/Magisk-v31.0.apk workdir/magisk.apk

      - name: Zip final image
        run: |
          cd workdir
          zip -r ../lineageos-magisk.zip .

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: lineageos-gsi-magisk-22.2
          name: LineageOS GSI with Magisk v31.0
          files: lineageos-magisk.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean up
        run: rm -rf gsi magisk workdir lineageos-magisk.zip
        
